### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Auzgame** [HypnoticLOL/Hypnotics-Menu#1]
Is there any real difference between this one and cupityies?

**Comment by HypnoticLOL** [comment]
this one has colors and the one i am just releasing has built in anti skip, I will update mine more that cupidity but I use his tbh, mine is just a side project

**Comment by Auzgame** [comment]
@HypnoticLOL 
Didn't you say you barely knew js?

**Comment by HypnoticLOL** [comment]
Yes, yes I did. but the things I added/readded were from failedware or cupidity but arent in either of there menus
